# Generated by Django 2.2 on 2018-09-27 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('executed_at', models.DateTimeField()),
                ('game', models.CharField(max_length=15)),
                ('bet', models.CharField(max_length=4)),
                ('roll', models.IntegerField()),
                ('stake', models.DecimalField(decimal_places=8, max_digits=12)),
                ('multiplicator', models.DecimalField(decimal_places=2, max_digits=5)),
                ('profit', models.DecimalField(decimal_places=8, max_digits=12)),
                ('jackpot', models.BooleanField()),
                ('nounce', models.BigIntegerField()),
            ],
        ),
    ]
