# Generated by Django 2.2 on 2018-09-27 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_auto_20180927_1316'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bettor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=127)),
            ],
        ),
        migrations.AddField(
            model_name='bet',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='service.Bettor'),
        ),
    ]
