# Generated by Django 2.2 on 2018-09-27 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_auto_20180927_1449'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bet',
            old_name='user',
            new_name='bettor',
        ),
    ]
