# Generated by Django 2.2 on 2018-09-28 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_auto_20180927_1451'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bet',
            unique_together={('bettor', 'nounce')},
        ),
    ]
