# Generated by Django 2.2 on 2018-09-28 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_auto_20180928_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='balance_after',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='bet',
            name='balance_before',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=12),
        ),
    ]
