# Generated by Django 2.2 on 2018-09-28 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_auto_20180928_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='client_seed',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='bet',
            name='server_hash',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='bet',
            name='server_seed',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
